### ISSUE TITLE
Meteor 3.0-beta.6

### ISSUE THREAD

**Issue by paulincai** [zodern/fix-async-stubs#1]
Updated project to this version and started to see ```Method stub (getUserMethod) took too long and could cause unexpected problems. Learn more at https://github.com/zodern/fix-async-stubs/#limitations``` on a couple of methods, triggered at queueStubsHelpers.js line 111.

I only user server side methods.
Example of a method call (from the client) that triggers the message ( with Redux ):

```
const getUser = _id => {
  return dispatch => {
    Meteor.callAsync('getUserMethod', { _id })
      .then(res => dispatch({
        type: GET_USER,
        payload: res
      }))
      .catch(err => console.log(err))
  }
}
```

I added ```fix-async-stubs``` as a local package and modified the package.js to accept Meteor 3 and now, I get the same message twice. Once from the client.js (line 95) and once from queueStubsHelpers.js and once from the 
![Screenshot 2024-03-12 at 10 10 28 PM](https://github.com/zodern/fix-async-stubs/assets/26188915/377e9325-e343-4103-a473-5f948677e34a)

![Screenshot 2024-03-12 at 10 11 36 PM](https://github.com/zodern/fix-async-stubs/assets/26188915/b90344f4-ee16-4d90-b5c0-3997281b55ac)

I don't know if this package is supposed to be used with Meteor 3, however, Meteor 3 presents the message which indicated the need to install this package (as exemplified above).

**Comment by zodern** [comment]
This package is only for Meteor 2. The solution is integrated into Meteor 3. I think the next beta of Meteor 3 will fix the warning.

**Comment by harry-73** [comment]
Perhaps, it could be good to put it in the README. I am using the beta 7 and the warning is still present.
